apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome
  labels:
    app: selenium-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-chrome
  template:
    metadata:
      labels:
        app: selenium-chrome
    spec:
      containers:
      - name: selenium-chrome
        image: selenium/standalone-chrome:latest
        ports:
        - containerPort: 4444
        - containerPort: 5900
        env:
        # - name: SE_NODE_MAX_SESSIONS
        #   value: "1" # 可根據需求設置環境變數
        - name: SE_NODE_OVERRIDE_MAX_SESSIONS
          value: "false"