apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome
  labels:
    app: selenium-chrome
spec:
  selector:
    app: selenium-chrome
  ports:
  - name: web
    protocol: TCP
    port: 4444
    targetPort: 4444
  - name: vnc
    protocol: TCP
    port: 5900
    targetPort: 5900
  type: ClusterIP